### ISSUE TITLE
How to use `(import (srfi sicp))` in Apple App Store for MacOS LispPad.app Version 1.6.0 (1226)

### ISSUE THREAD

**Issue by jonBoone** [objecthub/swift-lispkit#13]
What is the best way to be able to use the `(srfi sicp)` support in the MacOS LispPad.app Version 1.6.0 (1226)?

Has a new version with that support been submitted to the MacOS App Store yet?

Thanks in advance!

FYI, I'm hoping to use this on both Intel and Apple Silicon (M1) MacBooks.

**Comment by objecthub** [comment]
Not yet! Only the iOS version of LispPad supports SRFI 216 via (srfi 216).
I will submit a new version for macOS in the coming week. If you want to use this library in the meantime already, you can do the following:

1. Download [216.sld](https://raw.githubusercontent.com/objecthub/swift-lispkit/master/Sources/LispKit/Resources/Libraries/srfi/216.sld) into the directory in which you store the source code of a Scheme application (let's assume it's `program.scm`)
2. At the top of `program.scm`, insert the following instructions:
    ```scheme
    (load "<absolute path to 216.sld>") ; make (srfi 216) known to LispKit
    (import (srfi 216)) ; import (srfi 216)
    ```

I am aware that SRFI 216 requires the library to be called (srfi sicp). Will be fixed when this is submitted to the AppStore.

There's also currently two "load" related bugs: one in LispPad (when the "Play" button in the editor is clicked), requiring that `(load (path (source-directory) "216.sld"))` needs to be replace by `(load "<absolute path to 216.sld>")` and one in LispKit where `load` does not return a result. Both will be fixed with the next submission to the AppStore.

**Comment by objecthub** [comment]
It looks like Apple reviews AppStore submissions even on the weekend. So, you don't need the workaround and you can just download LispPad 1.6.1 from the AppStore. A simple `(import (srfi sicp))` should do the trick.
